[package]
name = "genesys"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
inquire = "0.9.1"
itertools = "0.14.0"
reqwest = "0.12.23"
serde = "1.0.226"
serde_json = "1.0.145"
tap = "1.0.1"
tokio = { version = "1", features = ["full"] }
